import { Quiz } from '@/types/quiz';

export const generatePDF = async (
  quiz: Quiz,
  includeAnswers: boolean = false
): Promise<void> => {
  // Dynamically import html2pdf
  const html2pdf = (await import('html2pdf.js')).default;

  // Create a container for the PDF content
  const container = document.createElement('div');
  container.style.fontFamily = 'Arial, sans-serif';
  container.style.padding = '40px';
  container.style.maxWidth = '800px';
  container.style.margin = '0 auto';

  // Header
  container.innerHTML = `
    <div style="text-align: center; margin-bottom: 40px; border-bottom: 2px solid #4338ca; padding-bottom: 20px;">
      <h1 style="font-size: 24px; color: #1e1b4b; margin: 0 0 8px 0;">${quiz.quiz_metadata.title}</h1>
      <p style="color: #6366f1; margin: 4px 0; font-size: 14px;">
        ${quiz.quiz_metadata.subject} | ${quiz.quiz_metadata.academic_level} | ${quiz.quiz_metadata.language}
      </p>
      <p style="color: #64748b; margin: 4px 0; font-size: 12px;">
        Total Questions: ${quiz.quiz_metadata.total_questions} | Duration: ${quiz.quiz_metadata.duration_minutes} minutes
      </p>
    </div>
  `;

  // Questions
  const questionsHTML = quiz.questions.map((q, index) => {
    const optionLabels = ['A', 'B', 'C', 'D', 'E', 'F'];
    const optionsHTML = q.options.map((opt, i) => `
      <div style="display: flex; align-items: flex-start; gap: 12px; margin: 8px 0; padding: 8px; ${includeAnswers && i === q.correct_answer_index ? 'background-color: #dcfce7; border-radius: 4px;' : ''}">
        <span style="font-weight: bold; min-width: 24px;">${optionLabels[i]}.</span>
        <span>${opt}</span>
        ${includeAnswers && i === q.correct_answer_index ? '<span style="color: #16a34a; margin-left: auto;">✓</span>' : ''}
      </div>
    `).join('');

    const answerSection = includeAnswers ? `
      <div style="margin-top: 16px; padding: 12px; background-color: #f1f5f9; border-radius: 4px; border-left: 3px solid #6366f1;">
        <strong style="color: #4338ca;">Answer: ${optionLabels[q.correct_answer_index]}</strong>
        <p style="margin: 8px 0 0 0; font-size: 13px; color: #475569;">${q.explanation}</p>
      </div>
    ` : '';

    return `
      <div style="margin-bottom: 32px; page-break-inside: avoid;">
        <div style="display: flex; align-items: flex-start; gap: 12px; margin-bottom: 12px;">
          <span style="background-color: #4338ca; color: white; width: 28px; height: 28px; border-radius: 4px; display: flex; align-items: center; justify-content: center; font-weight: bold; font-size: 14px; flex-shrink: 0;">
            ${index + 1}
          </span>
          <div>
            <span style="background-color: #e0e7ff; color: #4338ca; padding: 2px 8px; border-radius: 4px; font-size: 11px; margin-right: 8px;">
              ${q.cognitive_level}
            </span>
            <span style="color: #64748b; font-size: 12px;">[${q.marks} marks]</span>
          </div>
        </div>
        <p style="margin: 0 0 16px 40px; line-height: 1.6; font-size: 14px;">${q.stem}</p>
        <div style="margin-left: 40px;">
          ${optionsHTML}
        </div>
        ${answerSection}
      </div>
    `;
  }).join('');

  container.innerHTML += questionsHTML;

  // Footer
  container.innerHTML += `
    <div style="text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 11px;">
      Generated by Exam Prep Gen | ${new Date().toLocaleDateString()}
    </div>
  `;

  // Generate PDF
  const options = {
    margin: 10,
    filename: `${quiz.quiz_metadata.title.replace(/[^a-zA-Z0-9]/g, '_')}_${includeAnswers ? 'with_answers' : 'questions_only'}.pdf`,
    image: { type: 'jpeg' as const, quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true },
    jsPDF: { unit: 'mm' as const, format: 'a4' as const, orientation: 'portrait' as const }
  };

  await html2pdf().set(options).from(container).save();
};
