import { Quiz } from '@/types/quiz';
import jsPDF from 'jspdf';

export const generatePDF = async (
  quiz: Quiz,
  includeAnswers: boolean = false
): Promise<void> => {
  const doc = new jsPDF();
  const optionLabels = ['A', 'B', 'C', 'D', 'E', 'F'];
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  let yPos = margin;

  const addNewPageIfNeeded = (requiredSpace: number = 30) => {
    if (yPos + requiredSpace > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      yPos = margin;
    }
  };

  // Header
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 27, 75); // Dark indigo
  doc.text(quiz.quiz_metadata.title, pageWidth / 2, yPos, { align: 'center' });
  yPos += 10;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(99, 102, 241); // Indigo
  doc.text(
    `${quiz.quiz_metadata.subject} | ${quiz.quiz_metadata.academic_level} | ${quiz.quiz_metadata.language}`,
    pageWidth / 2,
    yPos,
    { align: 'center' }
  );
  yPos += 6;

  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139); // Slate
  doc.text(
    `Total Questions: ${quiz.quiz_metadata.total_questions} | Duration: ${quiz.quiz_metadata.duration_minutes} minutes`,
    pageWidth / 2,
    yPos,
    { align: 'center' }
  );
  yPos += 8;

  // Divider line
  doc.setDrawColor(67, 56, 202);
  doc.setLineWidth(0.5);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 15;

  // Questions
  for (let i = 0; i < quiz.questions.length; i++) {
    const q = quiz.questions[i];
    
    addNewPageIfNeeded(60);

    // Question number and cognitive level
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(67, 56, 202);
    doc.text(`${i + 1}.`, margin, yPos);
    
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(99, 102, 241);
    doc.text(`[${q.cognitive_level}]`, margin + 10, yPos);
    
    doc.setTextColor(100, 116, 139);
    doc.text(`[${q.marks} marks]`, margin + 40, yPos);
    yPos += 7;

    // Question stem (clean LaTeX for PDF - simple text version)
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(30, 30, 30);
    
    const cleanStem = q.stem.replace(/\$([^$]+)\$/g, '$1');
    const stemLines = doc.splitTextToSize(cleanStem, contentWidth - 10);
    doc.text(stemLines, margin + 5, yPos);
    yPos += stemLines.length * 5 + 5;

    // Options
    for (let j = 0; j < q.options.length; j++) {
      addNewPageIfNeeded(10);
      
      const isCorrect = j === q.correct_answer_index;
      const cleanOption = q.options[j].replace(/\$([^$]+)\$/g, '$1');
      
      if (includeAnswers && isCorrect) {
        doc.setFillColor(220, 252, 231); // Light green
        doc.rect(margin + 5, yPos - 4, contentWidth - 10, 7, 'F');
      }
      
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(50, 50, 50);
      doc.text(`${optionLabels[j]}.`, margin + 8, yPos);
      
      doc.setFont('helvetica', 'normal');
      const optionLines = doc.splitTextToSize(cleanOption, contentWidth - 25);
      doc.text(optionLines, margin + 18, yPos);
      
      if (includeAnswers && isCorrect) {
        doc.setTextColor(22, 163, 74);
        doc.text('✓', pageWidth - margin - 10, yPos);
      }
      
      yPos += optionLines.length * 5 + 3;
    }

    // Answer explanation (if including answers)
    if (includeAnswers) {
      addNewPageIfNeeded(25);
      yPos += 3;
      
      doc.setFillColor(241, 245, 249); // Light slate
      doc.rect(margin + 5, yPos - 4, contentWidth - 10, 20, 'F');
      
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(67, 56, 202);
      doc.text(`Answer: ${optionLabels[q.correct_answer_index]}`, margin + 8, yPos);
      yPos += 5;
      
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(71, 85, 105);
      const cleanExplanation = q.explanation.replace(/\$([^$]+)\$/g, '$1');
      const explanationLines = doc.splitTextToSize(cleanExplanation, contentWidth - 20);
      doc.text(explanationLines.slice(0, 2), margin + 8, yPos);
      yPos += Math.min(explanationLines.length, 2) * 4 + 8;
    }

    yPos += 10;
  }

  // Footer
  addNewPageIfNeeded(20);
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.3);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 8;
  
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(
    `Generated by Exam Prep Gen | ${new Date().toLocaleDateString()}`,
    pageWidth / 2,
    yPos,
    { align: 'center' }
  );

  // Save
  const filename = `${quiz.quiz_metadata.title.replace(/[^a-zA-Z0-9]/g, '_')}_${includeAnswers ? 'with_answers' : 'questions_only'}.pdf`;
  doc.save(filename);
};
